version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/railsapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  pgadmin:
    image: dpage/pgadmin4:5.5
    environment:
     PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
     PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
     PGADMIN_LISTEN_PORT: "${PGADMIN_LISTEN_PORT}"
    ports:
      - "5050:80"
    volumes:
     - pgadmin-data:/var/lib/pgadmin
    links:
     - "db:pgsql-server"
volumes:
  db-data:
  pgadmin-data:

